[profile.default]
solc_version = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
auto_detect_solc = true
via_ir = true
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
